### DISCUSSION TITLE
Icon Button svg fill comment

### DISCUSSION THREAD

**Discussion by Deufel** [felix-bohlin/ui#80] [Q&A] [answered]
# Should  the icon button SVG fill set to current color? 

I am using Lucid Icons and im not sure that the fill = current collor is always the desired look, for an example here is the mailbox icon

<img width="271" alt="Screenshot 2025-01-11 at 1 22 54 PM" src="https://github.com/user-attachments/assets/e8bfeb4a-0960-49d0-9f07-210765e1e900" />

But if i comment that out, I get the icon as it is intended to look (more or less)

## button-variants.css
```css
    /* Icon */
    &:where(:has(svg), &.icon-only) {
        gap: 1ex;

        & svg {
            /* fill: currentColor; */
        }
    }

```
<img width="248" alt="Screenshot 2025-01-11 at 1 22 00 PM" src="https://github.com/user-attachments/assets/49745af0-86a6-4aad-8edd-2f574e6b56f8" />

I can live with this if that is just the nature of the some icons vs lucid but just wanted to check that this is intended. Thanks

**Comment by felix-bohlin** [comment]
I think this is one of those cases where (by design), you'd have to modify the code to fit your needs. Icons are quirky! 😄 The way to circumvent that on a library level would be to:
1. provide all the icons myself (but that would result in lock-in)
2. add fixes for every type of icon pack we find along the way
3. leave it open for people to modify it to their needs in their respective projects 

I'm obviously in camp #3, but if there's something inherent to ex solid icons vs outlined icons specifically, I would like to do some fix for that.

Either way, I'll look into Lucid icons and how they do it, thanks for taking the time @Deufel ❤️

Do you have any thoughts on this?

**Comment by Deufel** [comment, marked as answer]
Thanks for the quick response! Yeah I would say that 1 and 2 are not the best way to go nor maintainable.  Im a bit new at all this stuff so I am usually unsure if the issue I am having is by design or if it is my poor implementation. I think that this boils down to stroke based icons vs fill based icons. 

Maybe something like the following would allow the library to be more general purpose with out over committing to support every icon under the sun.

```css
/* Icon */
    &:where(:has(svg), &.icon-only) {
        gap: 1ex;

        & svg:not([fill="none"]) {
            fill: currentColor;
        }

        & svg[stroke] {
            stroke: currentColor;
        }
    }
```
    
With Change:
<img width="458" alt="Screenshot 2025-01-13 at 12 12 54 PM" src="https://github.com/user-attachments/assets/fb165bc6-959d-4dbd-b002-bd91a19e0ce6" />

    
With Out (original):
<img width="430" alt="Screenshot 2025-01-13 at 12 20 33 PM" src="https://github.com/user-attachments/assets/4b6f4ac7-c4a1-495f-b784-71d444686b2d" />

*the log-in icon is a bit distorted because the fill is changed from none to currentColor*
