### ISSUE TITLE
Vertical scrollbar issue with dialog element

### ISSUE THREAD

**Issue by onokumus** [felix-bohlin/ui#129]
If I put the `dialog` element before the `table` element, there is no vertical scrollbar, but if I put it after the `table` element, there is a vertical scrollbar. 

Can you help me?

[Undesirable situation](https://onokumus.github.io/uitest101/)

[Desired situation](https://onokumus.github.io/uitest101/noerror.html)

Repo: 
https://github.com/onokumus/uitest101

**Comment by Deufel** [comment]
Im not sure this will help; but this reminded me of this recommendation for scroll behavior in a css reset [YouTube](https://youtu.be/cCAtD_BAHNw?t=252) where Keven Powell said that this helps with nested scroll behavior - maybe this will help with your issue. 


```css
@media (prefers-reduced-motion: no-preference) {
  : has (: target) {
    scroll-behavior: smooth;
  }
}
```

**Comment by onokumus** [comment]
After submitting this issue, I found the source of the problem.

`dialog` element

Firefox:
```css
dialog {
  display: block;
}

dialog:not([open]) {
 display: none;
}
```

Chrome:
```css
dialog {
  display: none;
}

dialog[open] {
  display: block;
}
```

styles are applied.

OPUI `dialog` element

```css
@layer components.has-deps {
  :where(dialog)[open] {
    opacity: 0;
  }

  :where(dialog)[open] {
    opacity: 1;
    transition: display .2s allow-discrete,margin-block-start .3s var(--ease-1),overlay .2s allow-discrete,opacity .2s var(--ease-out-1);
  }
}
```

It applies the styles. Since it does not add any `display` property, it does not take up space on the page. However,

```html
<dialog class="card">
...
</dialog>
```

if you assign the `.card` class,

```css
@layer components.base {
  :where(.card) {
    display: flex;
  }
}
```
because of the style, it takes up space on the page.
