### ISSUE TITLE
Theme questions

### ISSUE THREAD

**Issue by Deufel** [felix-bohlin/ui#188]
Maybe I am missing something here but why not use the following for the theme? 

This (for me) lets the device settings determine the style where the original did not. is the .light and .dark for explicit targeted preference declaration ? 

```css
@layer theme {
  html {   
    color-scheme: light dark;
  }

  :where(html) {
    --palette-hue: var(--oklch-cyan);
    --palette-hue-rotate-by: 5;
    --palette-chroma: 0.89;
```

vs 

```css
@layer theme {
  html {
    color-scheme: var(--color-scheme);
  }

  .light {
    --color-scheme: light;
  }
  .dark {
    --color-scheme: dark;
  }

  :where(html) {
    color-scheme: light dark;
```
